<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="9" time="0.109" timestamp="2022-02-15T16:22:15.964363" hostname="DESKTOP-S6D3M08"><testcase classname="test_first" name="test_1" time="0.001" /><testcase classname="test_first" name="test_2" time="0.001" /><testcase classname="test_first" name="test_3" time="0.001"><failure message="AssertionError: title does not match&#10;assert 'jenkins' in 'Jenkins is ci server'">def test_3():
        name = "jenkins"
        title = "Jenkins is ci server"
&gt;       assert name in title, "title does not match"
E       AssertionError: title does not match
E       assert 'jenkins' in 'Jenkins is ci server'

test_first.py:14: AssertionError</failure></testcase><testcase classname="test_four" name="test_responsecode200" time="0.001" /><testcase classname="test_four" name="test_responsecode404" time="0.001" /><testcase classname="test_second" name="test_login" time="0.001" /><testcase classname="test_second" name="test_checkout" time="0.001" /><testcase classname="test_second" name="test_logout" time="0.001" /><testcase classname="test_third.MyTestCase" name="test_something" time="0.003"><failure message="AssertionError: True != False">self = &lt;test_third.MyTestCase testMethod=test_something&gt;

    def test_something(self):
&gt;       self.assertEqual(True, False)  # add assertion here
E       AssertionError: True != False

test_third.py:6: AssertionError</failure></testcase></testsuite></testsuites>